### ISSUE TITLE
Slight improvement to the timer

### ISSUE THREAD

**Issue by Jorma17** [magicus/statuseffecttimer#12]
In my opinion the timer should show both minutes and seconds because ATM it's just too inaccurate. For example, when you have 2 minutes and 30 seconds left, the timer should be `2:30`, not `2m`. Otherwise a great mod.

**Comment by magicus** [comment]
I'll take under consideration. The problem is that if the text gets too wide, it does not neatly fit in the icon. So a time like `11:30` would be 5 characters long, and that would be a problem. Right now the maximum length is 3 (like in `11m`); but possible I can get 4 characters to work (so having like `9:30` would be ok, but for 10 minutes or above, keep the `10m` as of now). 

Another aspect is that having the seconds count down feels a bit stressful. It makes sense when there is just a short amount of time left, but having like Hero of the Village for 20 minutes and having every second count down would not make a good UI, I think. So maybe seconds should start showing when it's like 3 minutes left, or so.

This might be the tipping point for where I have to add a configuration screen to the mod. :-)

**Comment by magicus** [comment]
I will not implement this. Trying to squeeze in 4 or more characters will not look good.
