### ISSUE TITLE
1.19.4 doesnt show effects that dont show particles

### ISSUE THREAD

**Issue by threecerny** [magicus/statuseffecttimer#16]
non particles effects dont show  in the mod

**Comment by magicus** [comment]
This behavior is by design. 

The mod only overlays timers on existing vanilla badges. When using non-particle effects, vanilla does not show the status effect badges, so there is nothing for the mod to put an overlay on top of.

I assume that the vanilla behavior is also by design. It is not uncommon for servers to achieve some special effect in e.g. a minigame by giving players effects, but that is supposed to be "hidden" since it distracts from the purpose. In those cases, it would just be annoying if the badge were showing.
